<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AduanSeeder extends Seeder
{
    public function run()
    {
        DB::table('aduans')->insert([
            [
                'nama' => 'John Doe',
                'email' => 'johndoe@example.com',
                'judul' => 'Bullying di Kelas',
                'keterangan' => 'Laporan mengenai tindakan bullying yang terjadi di kelas X-A.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Jane Smith',
                'email' => 'janesmith@example.com',
                'judul' => 'Tindak Bullying di Lapangan',
                'keterangan' => 'Laporan mengenai insiden bullying yang terjadi saat olahraga.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'Yes',
                'status' => 'Selesai',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ramdan',
                'email' => 'ramdan@example.com',
                'judul' => 'Tindak Bullying di kantin',
                'keterangan' => 'Laporan mengenai insiden bullying yang terjadi saat di kantin.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'Yes',
                'status' => 'Ditolak',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ali Reza',
                'email' => 'alireza@example.com',
                'judul' => 'Penganiayaan di Koridor',
                'keterangan' => 'Laporan mengenai penganiayaan yang terjadi di koridor sekolah.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Maya Lestari',
                'email' => 'mayalestari@example.com',
                'judul' => 'Penipuan oleh Teman Kelas',
                'keterangan' => 'Laporan mengenai penipuan yang dilakukan oleh teman sekelas.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Budi Santoso',
                'email' => 'budisantoso@example.com',
                'judul' => 'Pelecehan oleh Guru',
                'keterangan' => 'Laporan mengenai pelecehan yang dilakukan oleh seorang guru.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Citra Wulandari',
                'email' => 'citrawulandari@example.com',
                'judul' => 'Makanan Berbahaya di Kantin',
                'keterangan' => 'Laporan mengenai makanan yang dijual di kantin yang berbahaya untuk kesehatan.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'Yes',
                'status' => 'Selesai',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Dwi Prasetyo',
                'email' => 'dwiprasetyo@example.com',
                'judul' => 'Kekerasan Fisik oleh Senior',
                'keterangan' => 'Laporan mengenai kekerasan fisik yang dilakukan oleh senior di sekolah.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Rina Amalia',
                'email' => 'rinaamalia@example.com',
                'judul' => 'Penyebaran Hoaks di Grup WhatsApp',
                'keterangan' => 'Laporan mengenai penyebaran hoaks yang terjadi di grup WhatsApp sekolah.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Fauzi Alif',
                'email' => 'fauzialif@example.com',
                'judul' => 'Pencurian Uang di Kelas',
                'keterangan' => 'Laporan mengenai pencurian uang yang terjadi di kelas X-B.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'Yes',
                'status' => 'Selesai',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Ika Sari',
                'email' => 'ikasari@example.com',
                'judul' => 'Buliing di Media Sosial',
                'keterangan' => 'Laporan mengenai bullying yang terjadi melalui media sosial.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Yusuf Hidayat',
                'email' => 'yusukhidayat@example.com',
                'judul' => 'Tindak Kekerasan di Lapangan Olahraga',
                'keterangan' => 'Laporan mengenai tindak kekerasan yang terjadi di lapangan olahraga.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'Yes',
                'status' => 'Ditolak',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Siti Nurhaliza',
                'email' => 'sitinarhaliza@example.com',
                'judul' => 'Penghinaan oleh Teman Kelas',
                'keterangan' => 'Laporan mengenai penghinaan yang dilakukan oleh teman sekelas.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'No',
                'status' => 'Dalam Penanganan',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Andi Supriyadi',
                'email' => 'andisupriyadi@example.com',
                'judul' => 'Penipuan Uang oleh Teman',
                'keterangan' => 'Laporan mengenai penipuan yang dilakukan oleh teman sekelas terkait uang.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'Yes',
                'status' => 'Ditolak',
                'token' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'kira',
                'email' => 'kira@example.com',
                'judul' => 'Penipuan Uang oleh Teman',
                'keterangan' => 'Laporan mengenai penipuan yang dilakukan oleh teman sekelas terkait uang.',
                'tanggal' => now(),
                'type' => 'Public',
                'is_read' => 'Yes',
                'status' => 'Ditolak',
                'token' => '111111',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

    }
}
